### ISSUE TITLE
Introduction blog post

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#1]
Write a blog post to introduce yourself to the community

**Comment by fharper** [comment]
@react-learner can you review it please? Use the suggestions function of Google Doc so it's easier for me to see what you changed (I want to improve my English writing skill) and I can decide what I accept or not (since some suggestions can modify the tone or what I wanted to convey).

I would love to publish it on Thursday. In the future, we will try to give you more time to edit our stuff :)

https://docs.google.com/document/d/1-eLyG5Ioae2VlUJYSPuZt9hNqD_ac1sAJldd-XlySao/edit#

**Comment by react-learner** [comment]
Done 😄  Google's suggestion markup is super obtrusive, so I recommend that you preview the document with all accepted changes by going to Tools->Review suggested edits, then clicking on Preview "Accept all" in the drop-down.

**Comment by fharper** [comment]
I like it that way, it's why I used Google Doc. It's easier to see what you suggest and what I wrote, as I probably don't remember exactly mine 😂

**Comment by fharper** [comment]
The published version is at https://blog.meilisearch.com/fred/
