### ISSUE TITLE
Language pipelines call to action

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/devrel#114]
## Tokenizer

Recently a [new tokenizer](https://github.com/meilisearch/specifications/pull/2) was added to MeiliSearch. This tokenizer is **modular**, meaning it is "simple" to add new language scripts to the pipelines.

## Objective 

Because of this, it would be nice if contributors added their scripts from their known languages. 

## Challenge

As it may not be too hard to implement ( not sure not good at rust ), there are still other parameters that come in the way. 

For example, how do we determine that a user's script is well done or if it makes the tokenization of that language worse? We will have to contact external native persons to verify the relevancy of the script. 

Essentially, creating a script is a whole process that has not to be defined yet.

## Core Process

After consulting with marin of the core team, he decided that they will first **wait for contributions or feedback on the matter** before creating the guideline that will determine all the needed steps to go from scripting to merging it into master.

Essentially, This is how the core team will address the contributions:
1. Wait for contributors to show interest in adding their script or/and wait for users to ask for a specific language to be added
2. Once we arrive at a threshold of contributions (YET TO BE DEFINED) they will create a guideline that needs to be followed from A to Z in order for their script to be added to the pipeline.

This guideline will for example ask for enough review from persons that are native to the language of the script.

 ## DevRel Process

To achieve this previous step, we need to make calls for action to users. Spread the word that they can improve MeiliSearch in the language they need or want to see implemented (and also that they might just come and give feedbacks on which language they would like to see implemented). 

Some suggestions on where to communicate about the subject: 
- Slack community
- Meilisearch main repo as an issue asking for contributors to try it out
- Maybe some specific reddit or twitter ?

**Comment by fharper** [comment]
> After consulting with marin of the core team, he decided that they will first **wait for contributions or feedback on the matter** before creating the guideline that will determine all the needed steps to go from scripting to merging it into master.

Actually, I would argue that it should be the other way around. We create the documentation to make it easier for people to do it, and the community will chime in and do them because we support them. WDYT @MarinPostma ? I see that as part of the company goals for 2021, specifically:
- Better contributor onboarding
- Consider all levels of expertise & experience

**Comment by MarinPostma** [comment]
Yup @fharper, I see no objection on principle, but there are a couple of things to take into account:
- First the tokenizer interface is not stable per se, we hacked together a first version with @LegendreM and it still needs some iteration before we expose an interface we are happy with. We'd like to optimize the pipelines we currently have before we anything else.
- We have a very tight schedule with the ongoing projects, and we aren't currently actively developing the tokenizer, we keep it to maintenance for the time being.

For the reasons above, and given that we barely have time to maintain 2 pipeline, we'd rather not add the overhead of working with contribution on that part of the project just now. This means that supporting more languages is not a short term (next couple months) priority, and our efforts should be invested elsewhere for the time being.

I hope you understand 😊

**Comment by fharper** [comment]
Make sense, I didn't have the background about that, thanks for sharing.

**Comment by fharper** [comment]
I'm closing it for now since we decided to not move forward. We can reopen once the tokenizer will be in a better shape.
