### ISSUE TITLE
Recruit a freelance technical translator

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#119]
To translate @qdequele blog posts

**Comment by qdequele** [comment]
Which ones?

**Comment by fharper** [comment]
Right now, the only one ready is the "Why we choose rust", but I was expecting new ones to be written in French also. I prefer you do whatever you are more comfortable with and have someone else translate them before we published them. Unless you tell me you want to translate them yourself to get better in English. Let me know what you want to do.

**Comment by ferdi05** [comment]
seems no longer relevant
