### ISSUE TITLE
Find a topic + dataset for a MeiliSearch demo

### ISSUE THREAD

**Issue by react-learner** [meilisearch/devrel#12]
Best way to learn about MeiliSearch (and show off its features at the same time) is to use some real-world data to make a functional and hopefully useful demo. Open to topic suggestions.

**Comment by react-learner** [comment]
One topic I'm considering is academic papers or medical research. I feel like these are often only accessible through clunky old search engines and someone could get some real use out of it, if I can find a comprehensive enough database.

**Comment by fharper** [comment]
I like it. You can also ask on Slack, maybe people already had good ideas.

**Comment by react-learner** [comment]
Now thinking a searchable database of song lyrics would be kind of a great way to show off our tech.

**Comment by fharper** [comment]
The idea of this task was for you to learn about MeiliSearch, but I don't think you need it anymore, so I'm closing this :)
