### ISSUE TITLE
Integrate the contribution information into the documentation site

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#124]

**Comment by fharper** [comment]
@react-learner is now working on it with his work on the documentation contribution documentation :)

**Comment by fharper** [comment]
I think it's done?

**Comment by fharper** [comment]
@react-learner, I think it's done?%

**Comment by fharper** [comment]
If so, please check the appropriate box at https://github.com/meilisearch/devrel/issues/17 after closing this issue.

**Comment by ferdi05** [comment]
not super self-explanatory, but a lot of work was done to improve contributions within the DevRel team in the past months.
We're not aware of any repo missing guidelines for contributors.
