### ISSUE TITLE
Blog post: MoMa demo

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#130]

**Comment by fharper** [comment]
blocked by #32

**Comment by fharper** [comment]
It's not published yet :)

Did @react-learner reviewed it? Once he did, you can publish it.

**Comment by fharper** [comment]
https://blog.meilisearch.com/demo-moma/

**Comment by CaroFG** [comment]
Should we close it?

**Comment by fharper** [comment]
Weird, it should have closed when I moved it in Completed column
