### ISSUE TITLE
Tutorial: pagination

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#131]

**Comment by bidoubiwa** [comment]
see https://github.com/meilisearch/documentation/issues

**Comment by fharper** [comment]
You meant https://github.com/meilisearch/documentation/issues/561 ?

@CaroFG you already have some good material there. Let's not close the one in the documentation repo yet.

@bidoubiwa : FYI, we created it here since this will not go on the documentation doc, or we are not sure yet if it will be on the blog or not. Our way of managing those and the subtle difference was explained during the follow-up meeting where @react-learner spoke about the reorganization of the doc, but we will make all those things public, hopefully during Q1 where we have a lot of writing to do about how we operate as a team!

**Comment by react-learner** [comment]
I think a pagination guide would be great for the docs site, so I'm following this.

**Comment by CaroFG** [comment]
`MeiliSearch was not made for pagination. The idea is that you never have to "go to page 2".` We don't want to encourage pagination, so we won't make a tutorial about it.
