### ISSUE TITLE
How to update MeiliSearch

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#132]

**Comment by CaroFG** [comment]
Since it's really clear on the documentation, we decided it's no longer necessary to create a specific tutorial for it.

**Comment by CaroFG** [comment]
Guide for the documentation on how to update MeiliSearch

**Comment by CaroFG** [comment]
@react-learner you tell me if it's a how to or a guide :)

**Comment by fharper** [comment]
It's not completed until it's merged :)
