### ISSUE TITLE
Career development resources for my team

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#140]
It can be books, online video courses, in-person training, a simple blog article, an internal workshop or mentoring or anything that will help them learned the skills they need to continue to do an excellent job, but also the topics they mentioned wanting to learn more about. For now, here are the topics:

- [x] Analytics (mostly about websites)
- [x] Best practices & business strategies for great documentation/online presence
- [x] Cloud computing
- [x] Developer Relations
- [x] DevOps concepts
- [x] GitHub (mostly actions or workflows)
- [x] Leadership
- [x] Open Source Community (creating, growing and managing)
- [x] Open Source (software development, philosophy, business-wise)
- [x] Personal Branding
- [x] Public Speaking
- [x] Rust programming language
- [x] Search Engine Development
- [x] Software Development
- [x] Technical Writing

**Comment by fharper** [comment]
Obviously, for personal branding I suggest this book from this lovely author: [Success in Programming, How to Gain Recognition, Power, and Influence Through Personal Branding](https://www.apress.com/us/book/9781484200025). The title and cover sucks, but the content is A1!

**Comment by fharper** [comment]
FYI @react-learner & @CaroFG: I'm adding what I've found here so anyone can chime in and it could help others. I'm making a list of those and budget needed. I will check with you the suggestions before buying them, but feel free to add comments here, whether you like the suggestions I have, don't or have one of your own.

**Comment by fharper** [comment]
For generic Software Development, I suggest [The Clean Coder: A Code of Conduct for Professional Programmers](https://www.goodreads.com/book/show/10284614-the-clean-coder) for behavioural skill & [Clean Code: A Handbook of Agile Software Craftsmanship](https://www.goodreads.com/book/show/3735293-clean-code) for technical skill.

**Comment by fharper** [comment]
For Developer Relations, I suggest [The Developer Advocacy Handbook](https://developer-advocacy.com/) (free resources online - no need to buy him a coffee, I bought him enough drinks 🤣) & [The Business Value of Developer Relations: How and Why Technical Communities Are Key to Your Success](https://www.goodreads.com/book/show/40167835-the-business-value-of-developer-relations).

**Comment by fharper** [comment]
For Open Source Software, I suggest [Working in Public: The Making and Maintenance of Open Source Software](https://www.goodreads.com/book/show/54216469-working-in-public) & Forge Your Future with Open Source.

**Comment by baskarmib** [comment]
For Leadership I would suggest these by John Maxwell.
https://www.goodreads.com/book/show/39704795-developing-the-leader-within-you-2-0?from_search=true&from_srp=true&qid=5E06eAsmPf&rank=2
https://www.goodreads.com/book/show/40590293-leadershift
Also most of the free content in John Maxwell Podcast.

**Comment by fharper** [comment]
Thanks @baskarmib, I didn't know this author!

**Comment by fharper** [comment]
For leadership, I also suggest [Leaders Eat Last](https://www.goodreads.com/book/show/16144853-leaders-eat-last) & [Start with Why: How Great Leaders Inspire Everyone to Take Action](https://www.goodreads.com/book/show/7108725-start-with-why).

**Comment by fharper** [comment]
For DevOps, I suggest [The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win](https://www.goodreads.com/book/show/17255186-the-phoenix-project) & [The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations](https://www.goodreads.com/book/show/26083308-the-devops-handbook)

**Comment by fharper** [comment]
For public speaking I suggest [Demystifying Public Speaking](https://www.goodreads.com/book/show/32784222-demystifying-public-speaking) & [Public Speaking for Success](https://www.goodreads.com/book/show/39998.Public_Speaking_for_Success)

**Comment by fharper** [comment]
For Rust, I suggest [The Rust Programming Language](https://doc.rust-lang.org/book/) (free online resource) & the Udemy courses [Rust Programming For Beginners](https://www.udemy.com/course/rust-coding-for-beginners/) for new software developers & [The Rust Programming Language for advance developers](https://www.udemy.com/course/rust-lang/)

**Comment by fharper** [comment]
For Technical Writing, I suggest [The Developer's Guide to Content Creation](https://www.stephaniemorillo.co/product-page/the-developer-s-guide-to-content-creation)

**Comment by fharper** [comment]
For community, I suggest [People Powered: How Communities Can Supercharge Your Business, Brand, and Teams](https://www.goodreads.com/book/show/44442030-people-powered)

**Comment by fharper** [comment]
For GitHub Actions & Workflows, I suggest the udemy course [The Complete GitHub Actions & Workflows Guide](https://www.udemy.com/course/github-actions/)

**Comment by fharper** [comment]
For Cloud Computing, I suggest the udemy course [Cloud Computing Concepts](https://www.udemy.com/course/cloud-computing-concepts/)

**Comment by fharper** [comment]
For Analytics, I suggest the udemy course [Google Analytics for Beginners | Hands-On Training Course](https://www.udemy.com/course/google-analytics-insights/)

**Comment by fharper** [comment]
I'm struggling to find resources for "Best practices & business strategies for great documentation/online presence" @react-learner

**Comment by fharper** [comment]
Same for "Search Engine Development" @react-learner . I asked our core team, we'll see, but I assume there isn't much out there, since the content is about SEO when you talk about search engines...

**Comment by fharper** [comment]
I have a pretty good list that I'll try to split during the year. Need to approve the budget with @tpayet !

**Comment by fharper** [comment]
Budget was approved by @tpayet !

**Comment by fharper** [comment]
For building a search engine, there is not straightforward resources. There are still fundamental principles and blog posts that could help. Those are based on @MarinPostma suggestions (I cannot valide as I don't have the knowledge, but I 100% trust Marin!):

- [Algolia's blog](https://www.algolia.com/blog/) is a great source of information
- [bucket sorting](https://en.wikipedia.org/wiki/Bucket_sort)
- [data structures blog post](https://blog.burntsushi.net/transducers/) by burntsushi
- Levenshtein [automaton](https://en.wikipedia.org/wiki/Levenshtein_automaton) & [distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to understand typo tolerance
- [reverses indexes ](https://en.wikipedia.org/wiki/Reverse_index)
- [tf-idf](https://en.wikipedia.org/wiki/Tf–idf) & [BM25 algorithms](https://en.wikipedia.org/wiki/Okapi_BM25) (we don't use BM25 in MeiliSearch)

**Comment by fharper** [comment]
I will consider "Best practices & business strategies for great documentation/online presence" resources done with your ticket to [Write the Doc](https://www.writethedocs.org/conf/) which I think is the place to learn about that for now.

**Comment by fharper** [comment]
You will soon start to receive the resources based on the yearly plan I shared with you so I consider this issue close. It doesn't mean that you will stop having my support and resources to help you learn new things for your role and continue your career development. If you find anything (book, workshop, online video course, conference...) that can help you in your job, please let me know on Slack or during our 1:1. This one was a lot more work since it was the first one :D
