### ISSUE TITLE
Fred's long onboarding

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#16]
List of things I need to know that are not management related for my own onboarding at Meili:

*   [x] Setup new computer
*   [x] Read Notions
*   [x] Review Orbit
*   [x] Review Mention
*   [x] Read the [documentation](https://github.com/meilisearch/documentation) & give feedback
*   [x] Play with [MeiliSearch](https://github.com/meilisearch/MeiliSearch), build it locally & give feedback
*   [ ] Read the [blog](https://blog.meilisearch.com/) posts
*   [ ] Test de deployments
    *   [x] [DigitalOcean](https://github.com/meilisearch/meilisearch-digital-ocean)
    *   [ ] [Kubernetes](https://github.com/meilisearch/meilisearch-kubernetes)
*   [ ] Test the demo apps
    *   [x] [Boardgame](https://github.com/meilisearch/boardgame-demo)
    *   [ ] [Crates](https://github.com/meilisearch/finding-crates)
    *   [x] [La Redoute](https://github.com/meilisearch/demo-laredoute)
    *   [ ] [PyPI](https://github.com/meilisearch/finding-pypi)
    *   [ ] [RubyGems](https://github.com/meilisearch/finding-rubygems)
*   [ ] Test the integrations
    *   [ ] [.NET](https://github.com/meilisearch/meilisearch-dotnet)
    *   [ ] [Deno](https://github.com/meilisearch/meilisearch-deno)
    *   [ ] [Documentations Search Bar](https://github.com/meilisearch/docs-searchbar.js)
    *   [ ] [Frontend Search Bar](https://github.com/meilisearch/searchbar.js)
    *   [ ] [Go](https://github.com/meilisearch/meilisearch-go)
    *   [ ] [InstantSearch](https://github.com/meilisearch/instant-meilisearch)
    *   [ ] [Java](https://github.com/meilisearch/meilisearch-java)
    *   [ ] [Laravel Scout](https://github.com/meilisearch/meilisearch-laravel-scout)
    *   [ ] [JavaScript](https://github.com/meilisearch/meilisearch-js)
    *   [ ] [PHP](https://github.com/meilisearch/meilisearch-php)
    *   [ ] [PHP Symphony](https://github.com/meilisearch/meilisearch-symfony)
    *   [ ] [Python](https://github.com/meilisearch/meilisearch-python)
    *   [ ] [React](https://github.com/meilisearch/meilisearch-react)
    *   [ ] [Ruby](https://github.com/meilisearch/meilisearch-ruby)
    *   [ ] [Rust](https://github.com/meilisearch/meilisearch-rust)
    *   [ ] [Swift](https://github.com/meilisearch/meilisearch-swift)
    *   [ ] [VuePress](https://github.com/meilisearch/vuepress-plugin-meilisearch)
    *   [ ] [Wordpress](https://github.com/meilisearch/meilisearch-wordpress)
*   [ ] Test the tools
    *   [ ] [Documentations Scraper](https://github.com/meilisearch/docs-scraper)
    *   [ ] [GitHub Issues Scraper](https://github.com/meilisearch/github-issues-scraper)
    *   [x] [Icon Dataset Faker](https://github.com/meilisearch/icon-dataset-faker)
    *   [ ] [Reddit Fetche](https://github.com/meilisearch/subreddit-fetcher)r
*   [ ] Check others repo
    *   [ ] [API](https://github.com/meilisearch/MeiliSearch-private)
    *   [ ] [Backlog](https://github.com/meilisearch/backlog/issues)
    *   [ ] [Chiquitita](https://github.com/meilisearch/chiquitita)
    *   [ ] [Discuss](https://github.com/meilisearch/discuss)
    *   [ ] [Integrations Guides](https://github.com/meilisearch/integration-guides)
    *   [x] [Integrations Scripts](https://github.com/meilisearch/integration-scripts)
    *   [x] [Landing](https://github.com/meilisearch/landing)
    *   [x] [Landing v2](https://github.com/meilisearch/new-landing)
    *   [ ] [Madness](https://github.com/meilisearch/madness)
    *   [ ] [MeiliES](https://github.com/meilisearch/MeiliES)
    *   [ ] [Raft](https://github.com/meilisearch/raft)
    *   [ ] [Raft Metrics](https://github.com/meilisearch/raft-metrics)
    *   [ ] [RFC](https://github.com/meilisearch/specifications)
    *   [ ] [Rocket](https://github.com/meilisearch/Rocket)
    *   [ ] [Rocket Cors](https://github.com/meilisearch/rocket_cors)
    *   [x] [Sandbox Platform](https://github.com/meilisearch/sandbox-platform)
    *   [x] [Sandbox Platform v2](https://github.com/meilisearch/sandbox-v2)
    *   [x] [Test CI](https://github.com/meilisearch/test-ci)
    *   [ ] [Tokenizer](https://github.com/meilisearch/Tokenizer)
    *   [ ] [Vigil Status](https://github.com/meilisearch/vigil-status)
*   [ ] Learn Rust

**Comment by CaroFG** [comment]
I know it's your issue, but why Ruby?

**Comment by fharper** [comment]
For whatever reason, I always say Ruby instead of Rust. I think it's wishful thinking 🤣

**Comment by fharper** [comment]
I really need to spend more time trying to make meilisearch compile on my laptops (I have the same error on my intel macbook, and m1 too)

**Comment by fharper** [comment]
I didn't do everything I wanted to do, but it's good for now...
