### ISSUE TITLE
List of devrel tasks for our new designer

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#161]
Can we use this issue to list what we would need from our new designer. I'll make a recap and priority list to discuss with @qdequele before she join.

**Comment by fharper** [comment]
- Documentation revamp
- Devrel logo :)
- Stickers
- Blog posts images
- Revamp our demos...

**Comment by CaroFG** [comment]
Special project announcement :)

**Comment by fharper** [comment]
MeiliSearch Default Web Interface

**Comment by fharper** [comment]
a nice 404 page

**Comment by fharper** [comment]
I had a meeting with @qdequele about those. Since she is starting next week, if we have other suggestions, we'll be able to share them directly with her!
