### ISSUE TITLE
Create a MeiliSearch Rails integration

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#163]

**Comment by CaroFG** [comment]
We have a first working version and have started working with issues. Hereafter, you can track the progress here: https://github.com/meilisearch/meilisearch-rails/issues

**Comment by dichotommy** [comment]
Congrats on finishing this @CaroFG !

**Comment by CaroFG** [comment]
It's not completely finished yet, but I'm close to the end 😄
