### ISSUE TITLE
Integrate the MeiliSearch scout driver into Laravel Scout

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#164]
I will need to learn a bit more about Laravel Scout first, and see if they are open to have other drivers right inside the main project. I would assumed it's the case...

The idea is to add MeiliSearch as an alternative driver to [Laravel Scout](https://github.com/laravel/scout) as right now, the default is Algolia.

**Comment by fharper** [comment]
@curquiza FYI

**Comment by robsontenorio** [comment]
https://github.com/meilisearch/meilisearch-laravel-scout ?

**Comment by fharper** [comment]
@robsontenorio haha, thanks, but I'm talking about adding it to https://github.com/laravel/scout as a driver. Will update the issue description to be clearer :)

**Comment by fharper** [comment]
I'm closing this one since the integration is already discussing about that, and it is in their scope.
