### ISSUE TITLE
Create a centralized "Assets / Information" folder or repository for MeilISearch

### ISSUE THREAD

**Issue by eskombro** [meilisearch/devrel#166]
It would be really great if we had a single place where a few assets are stored and centralized, so everybody can use them. I am thinking of:

- Logos (different formats)
- Description of the product
- Short description of the product
- Video / presentation
- Category (or categories) normally used on an application form
- Keywords
- List of features (kind of one word or term features I.E. Typo-tolerant...)
...

If this resides on GitHub, we can all do suggestions and PRs to contribute, and the DevRel team can have an overview on it, so we vehiculate a coherent image of the product/company (good for us but also for people who don't work at Meili)

What do you think?

**Comment by fharper** [comment]
Good idea @eskombro !

**Comment by fharper** [comment]
I'm working on it, I was already adding the logos anyway

**Comment by eskombro** [comment]
I added `keywords` to the list :)

**Comment by fharper** [comment]
I will resubmit with HTML IMG tags instead of Markdown as GitHub doesn't permet import of CSS file so the logos are too big. Was working on my machine 🤣

But here we go https://github.com/meilisearch/devrel/blob/main/assets/information.md

**Comment by eskombro** [comment]
Thanks a lot @fharper !!! 🎉
