### ISSUE TITLE
Start office hours

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#168]
Office Hours are time people can RSVP to have a meeting with us (usually 30 minutes) to have a video chat.

I can do office hours on
- Public Speaking
- Developer Relations
- Contributing on OSS
- MeiliSearch obviously

@CaroFG can do them on MeiliSearch

By experience, I don't expect a lot of people using them, but it's another way for us to be reachable and it's also about perception.

**Comment by fharper** [comment]
Need to create a calendly events for that (should update my other ones also).

**Comment by fharper** [comment]
Blocked, waiting for @qdequele to let Léna create my office hours image. Let's be honest, I could start without, but by experience, it's way better with something visual.

**Comment by fharper** [comment]
I will start with no image for the promotion since Léna don't have 30-60 minutes for this. Should be fine, will just have less people (don't underestimate the strength of a good visual to catch the attention from people on social medias :) )

**Comment by ferdi05** [comment]
does not seem needed yet
