### ISSUE TITLE
Blog post: Automate Pull Requests merging with Bors

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#172]
Finish this blog post started in Ghost or let me know if you won't move forward with it.

**Comment by curquiza** [comment]
I will do it this week or the next one! Is it ok for you?

**Comment by fharper** [comment]
Next week we will publish the Moma blog post from Caro, so if it's ready for the week after it's nice. Once you have your draft ready, please ask Tommy to review it :)

**Comment by fharper** [comment]
@curquiza did you have time to finish this one?

**Comment by react-learner** [comment]
@curquiza I remember that you let us know the blog post was ready, it's I who didn't find the time to review it 😔
