### ISSUE TITLE
Create 2021 contribution sticker

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#183]
Let me know when it will be done so I can pay the artist and send them to print :)

**Comment by qdequele** [comment]
Who is in charge of that? Could we ask Lena for help on that?

**Comment by fharper** [comment]
@bidoubiwa is assigned to this task since the concept is her idea and she already worked with the designer.

We prefer to stick with the designer since we would like to keep the same style from the first contribution sticker: he is also really not expensive.

**Comment by bidoubiwa** [comment]
We need to pay before starting the procedure, I will be doing that we thomas tomorow.

**Comment by CaroFG** [comment]
Shall we close this?
