### ISSUE TITLE
Media appearance page

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#194]
Add a "MeiliSearch in the media" markdown file to this repo, where we list all the external sources where MeiliSearch was showcased: it can be from traditional media like the interview @bidoubiwa, the livestream that @CaroFG did with @fharper...

**Comment by fharper** [comment]
https://www.youtube.com/watch?v=SJl2UWfy1nk

**Comment by fharper** [comment]
https://www.salesforce.com/fr/resources/way-tv/way-of-learning/peer_learning_apprendre_des_autres_sophie_vigier/

**Comment by fharper** [comment]
https://www.bfmtv.com/economie/replay-emissions/tech-and-co/tech-co-lundi-15-fevrier_VN-202102150483.html

**Comment by fharper** [comment]
https://www.youtube.com/embed/KLZ5qZWcd5w?autoplay=0

**Comment by fharper** [comment]
https://www.youtube.com/watch?v=4aiUCYEOVgo&ab_channel=42Entrepreneurs

**Comment by fharper** [comment]
Can you add these in the markdown you created @CaroFG and close this issue please.

**Comment by CaroFG** [comment]
Should a create a new media appearance file? Because it's kind of different than mentions
