### ISSUE TITLE
List of talks experience

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#195]
Create a markdown file in this repo with a list of the talks you gave (hackathon, livestream today...) with some information like slides, recording... It will help to share this for CFP, showing your experience.

Something like the list of talks I put at https://fred.dev/speaking/

**Comment by fharper** [comment]
I don't see anything in devrel 😆

**Comment by CaroFG** [comment]
https://github.com/meilisearch/devrel/pull/203
