### ISSUE TITLE
Contact developers from external integrations

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#198]
Contact developers from external integrations, put them in relation with the integration team, and once our tests are conclusive, add them into a specific section in the documentation & integrations repo.

**Comment by fharper** [comment]
@curquiza can you give me the list of all the external integrations you have on your pipeline please.

If you already have the contact, please send me in private the info.

**Comment by curquiza** [comment]
- Yunno: https://github.com/YunoHost-Apps/meilisearch_ynh
- D language: https://github.com/aberba/meilisearch
- https://github.com/devtud/aio_meilisearch
- https://github.com/unionco/craft-meilisearch

😄

**Comment by fharper** [comment]
https://airbyte.io/destination/search/meilisearch/

**Comment by ferdi05** [comment]
asked @curquiza about it

**Comment by CaroFG** [comment]
After a month, only one maintainer has replied. The main problem raised to keep the integration up to date with MeiliSearch is keeping up with the changes. He is the only maintainer of the integration, but this can change in the near future. He pointed out that the new information in Community Slack integrations channels might help him be aware of MeiliSearch's changes.
