### ISSUE TITLE
Blog post: from security agent to developer

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#199]
I love your story @bidoubiwa, I think it would be cool to write a blog post about it. Obviously, if you want! If you don't, it's totally fine, just close this issue :)

**Comment by bidoubiwa** [comment]
I will think about it seriously and come back to you!

**Comment by bidoubiwa** [comment]
Hey! So I thought about this. I think I prefer not to use my life story in a corporate environment. If I create a blog post about it I would prefer it to be on my (if I will have one) blog.
