### ISSUE TITLE
Create a page where we list which companies are using MeiliSeach

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#204]
Should start with the one in https://www.notion.so/meilisearch/e6f9000cc10d4ee495a9db289de11223?v=64c4a6682ff64cbe853cbc597b675b11 (private, sorry) and the one shared in our internal Slack channel #meili-love (private also)

**Comment by CaroFG** [comment]
- [Hedira](https://www.hedira.io/) (source: https://meilicommunity.slack.com/archives/C01F44SSCCA/p1606344526015300)
- [JuiceBrothers] (https://juicebro.com/en/products/drinks-en/juices-en/) use MeiliSearch based filters (source: https://twitter.com/markdevri_es/status/1347178895271989250)

**Comment by fharper** [comment]
Let's add the ones shared in #meili-love also
