### ISSUE TITLE
Test ways to rebase our code while keeping the verified badge

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#218]
When we rebase on the GH site or using Bors, since the rebase create new commits, we lose the verified badge. I think it's important for the long term to keep those for security reason.

I know well git, but this is out of my scope, so I'll check this https://stackoverflow.com/questions/18874281/how-to-retain-commit-gpg-signature-after-interactive-rebase-squashing

**Comment by ferdi05** [comment]
@curquiza I don't really know about this, and I feel like it's more on your side than on DevRel's

**Comment by curquiza** [comment]
Fred wanted all the commits to be verified (i.e. signed) by the author on GitHub, but with bors it is complicated.
Don't know on which side it is, but not a priority from my POV

**Comment by ferdi05** [comment]
Should I close this?

**Comment by curquiza** [comment]
Yes, not really on the devrel team side, except if you think the non-signed commits can impact the image of MeiliSearch, but otherwise, I think it should come as a security issue. So not from the devrel team
