### ISSUE TITLE
Create a better 2-3 sentences description of MeiliSearch

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#225]
In the information.md file, there is a long (more medium than long) description about MeiliSearch and it feel disconnected. It's more like a bunch of marketing terms together. We would need a better 2-3 sentences to describe MeiliSearch.

**Comment by bidoubiwa** [comment]
Ah, I was thinking about it some time ago! I thought we do not emphasize enough the `simplicity` part of meilisearch. This is why we stand out in the open-source competition. A bit like stripe is in fact selling a documentation and not a product.
