### ISSUE TITLE
Update Charlotte speaker page

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#226]
In the events folder, there is a markdown named `charlotte.md`. Please fill it based on the `speaking-template.md` when you have time. It's for future events, that will make your life easier, and that may open yourself to new speaking opportunities.

**Comment by fharper** [comment]
PR with the template not merged yet https://github.com/meilisearch/devrel/pull/224

**Comment by bidoubiwa** [comment]
Hey, nice initiative! I prefer avoiding publishing my photo on GitHub though 😁

**Comment by bidoubiwa** [comment]
Hey nice initiative! I would prefer not to add personal information on GitHub (as bio and photo) but I can add non-personal thinks.

**Comment by fharper** [comment]
ok

**Comment by fharper** [comment]
Just to be sure @bidoubiwa, you know that when you speak at a conference they put your photo and bio on their website and it's public? So public speaking will be a problem about that.

**Comment by fharper** [comment]
Without information about the speaker, not sure it make sense to add a speaker page, but let's try it anyway :)

**Comment by fharper** [comment]
Closed by #235
