### ISSUE TITLE
Move our forum platform from GitHub Discussions to Discourse

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#231]
As decided in #21

**Comment by fharper** [comment]
GitHub Discussion API to export the previous discussions: https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
Discourse API to import the previous discussions: https://docs.discourse.org/

**Comment by CaroFG** [comment]
Plugin to create a link from a Github pull request or commit back to a Discourse post where it is mentioned.: https://github.com/discourse/discourse-github

**Comment by fharper** [comment]
After discussion with @tpayet & @qdequele, they don't want us to move to the right tool for our community discussion right now. It's still something I want us to do as it will help us do our work more efficiently once we have a bigger community: it will also give a way better experience to the community, which should be a priority for us. Hopefully, the transition to a new platform once we will have more people using our forums won't be too difficult :)
