### ISSUE TITLE
Create a small guide on how to Slack in a healthy way in a business

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#249]

**Comment by fharper** [comment]
It is not for the community but for employees since I'm the person using Slack and being remote for the longer. It will help people that aren't comfortable with Slack. It's important even if not devrel related, specially because we are hiring more and more, and hopefully, one day, people on different timezones.

**Comment by ferdi05** [comment]
Great idea, but I feel like this hould be a HR project. Closing this and sending the link to the HR team.
