### ISSUE TITLE
Champions program

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#284]
Resources: 

- https://www.youtube.com/watch?v=ujyIGwY0FA0
- https://devrelresourc.es/#devrel-activities-champion-programs

https://www.prisma.io/ambassador

- Space to thank contributors personally and learn more about them (e.g. https://appwrite.io/community)
- Interview them (e.g. https://github.com/meilisearch/discuss/discussions/23)
- Pay attention to the community members that keep showing up, nurture them, shine the spotlight on them and celebrate these outstanding community members to inspire others

**Comment by ferdi05** [comment]
Other programs that are worth looking at:

- AWS Heroes
- Java Champions
- GitHub Stars
- Stripe Community Experts

**Comment by shivaylamba** [comment]
I have also gone through a few other really successful programs like : 
1.  [Auth0 Ambassador Program](https://auth0.com/ambassador-program)
2. [Twilio Champions Program](https://www.twilio.com/champions)

Just like we define the 3 verticals of DevRel as Code, Community and Content, the Champions program can be focused on these 3 verticals and we can find contributors interested in either of these 3. 

Some of the initiatives can be described as follows : 
1. Content : Ability to demonstrate interest in creating or sharing technical content be it via blog posts, public speaking, or developer events ( conferences / meetups ) 
2. Code : Ability to showcase awesome hacks that can be built on top of Meilisearch
3. Community : Actively share about Meilisearch, support others.

**Comment by CaroFG** [comment]
We had a meeting today with @shivaylamba to discuss the program, we have another meeting this week. We agreed on creating a list of 10 possible candidates for the program, defining what the program will consist of at its inception, and creating a list of expected questions potential candidates might have. Progress can be tracked on [Notion](https://www.notion.so/meilisearch/Champions-Program-1bc46814acd341f9a36bc76912c66f0d) (private link), we'll update this issue when decisions are made.

**Comment by CaroFG** [comment]
We have not been very thorough in publishing our progress on GitHub. We'll henceforth do better.  
We had a meeting today with @shivaylamba:

-  We left out the idea of sending a survey to potential champions. We would like to send a survey after launching the program (not right after, but several months after) to collect feedback to help us improve it.
- Based on the [4 archetypes of champions programs](https://developerrelations.com/dev-rel/the-four-archetypes-of-developer-champion-programmes), we have decided to start with the "reward and motivate" and with the idea of growing to a "force multiplier one".
- We also agreed on the importance of making the champions comply with a Code of Conduct

Next steps:
- Create a pitch presentation of the program
- Send the questions to other companies' devrels for review

**Comment by CaroFG** [comment]
Members of the team can also follow the progress on this notion page: [Champions program log](https://www.notion.so/meilisearch/Champions-program-log-4419fc85a8734dcb8f46389ae28a4aa9) (__private link__)

**Comment by CaroFG** [comment]
In today's meeting, @shivaylamba and I worked on the roadmap of the program. We agreed to add more ideas and work on the goals and metrics before our next meeting on Thursday 24th.

**Comment by CaroFG** [comment]
We had a meeting today with @shivaylamba, we worked on the presentation: we decided on the slides each is going to present and agreed to write a script and give each other feedback about it. We also agreed on adding some missing information to the presentations (list of champions, selection criteria...). Once we are comfortable with the script we'll schedule a meeting with @ferdi05 to do the presentation.

**Comment by shivaylamba** [comment]
Hi @ferdi05 @CaroFG there is a tool known as CommonRoom (https://www.commonroom.io/) that is also commonly used as an alternative to Orbit. 
They have described a use-case document on building a champions program: https://docs.commonroom.io/discover-popular-use-cases/build-a-champions-program?utm_campaign=EM_Product_Onboarding&utm_medium=email&_hsmi=209938546&_hsenc=p2ANqtz-8CX-pfNqMgfZ1744GEVwV17UTpjkkZcoKzxN7VOwQrryxDXIIA2JpZi7nFfq-r53f_8Kni7iXuMCAWE3YFuskYiFzwDQ&utm_content=209938546&utm_source=hs_automation

It could be worth taking a look at.

**Comment by CaroFG** [comment]
With @Luna-meili 's arrival to the team, we have resumed work on the partner program. We have:
- decided on the name
- expanded the initial list of potential program members
- added more activities to the list
- contacted the design team who have been super reactive and have already sent design proposals
- defined how we would like our contributors' space on our site to look like

We don't want to reveal everything on GitHub, because we want to keep the "surprise factor" :D

**Comment by CaroFG** [comment]
A presentation of the program is to be made on December 21 to @tpayet, who needs to validate it before presenting it to the rest of Meilisearch team and launching the actual program.

**Comment by CaroFG** [comment]
Closing this because the program was launched with a Welcome session on January 30th. We presented it to the whole company on February 2nd.

This first session will be shorter (January - May). The next sessions will be longer (September-May).

**Comment by CaroFG** [comment]
Closing this because the program was launched with a Welcome session on January 30th. We presented it to the whole company on February 2nd.

This first session will be shorter (January - May). The next sessions will be longer (September-May).
