### ISSUE TITLE
Resources center

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#285]
- Focus on onboarding, documentation, tutorials
- To be designed for the new website

**Comment by ferdi05** [comment]
Some good ressources center as recommended by @qdequele 
- [Tailwind](https://tailwindcss.com/resources)
- [Ghost](https://ghost.org/resources/)
- [Strapi](https://strapi.io/resource-center)
- [Qovery](https://www.qovery.com/)

**Comment by ferdi05** [comment]
We can think big and start small (for instance getting everything that is non doc from the doc app), then iterate.
We need to define who has the technical responsibilities, who can tell what we can or cannot do.

**Comment by ferdi05** [comment]
Creating migration guides
 - to heroku

**Comment by ferdi05** [comment]
all of this is now part of #357 
closing it
