### ISSUE TITLE
Competitors benchmark

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#286]
Resources: https://ghost.org/alternatives/

**Comment by ferdi05** [comment]
Well I now realize that we're still lacking a proper performance benchmark.
I think it's something we plan to do soon.
So not going to close this one until then.

**Comment by ferdi05** [comment]
Putting the performance benchmark in a new issue

**Comment by ferdi05** [comment]
It's now [added in the documentation](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html)
