### ISSUE TITLE
Plan Q1-2022

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#290]
Evaluate developer relations initiatives

**Comment by ferdi05** [comment]
Use the Aquisition->Activation->Engagement->Retention framework

**Comment by ferdi05** [comment]
<img width="1294" alt="Capture d’écran 2021-12-15 à 14 41 07" src="https://user-images.githubusercontent.com/2602288/146197746-37ef1425-934c-49f7-80c5-ab386cd6f99d.png">
To keep in mind

**Comment by ferdi05** [comment]
Currently ongoing on [Notion](https://www.notion.so/meilisearch/Plan-Q1-2022-d6af758d43d744b5988accb957b17b1a) _(private page)_
