### ISSUE TITLE
Catch up with DevRel issues on GitHub

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#296]

**Comment by ferdi05** [comment]
I'm checking every issue, even the _closed_ ones (they could have been closed being incomplete or by mistake).
The list is [here](https://github.com/meilisearch/devrel/issues?q=is%3Aissue+), then sort by newest.
I'm starting by the newest to get to the oldest.

**Comment by ferdi05** [comment]
I reached #244, it seems that the next one is #242

**Comment by ferdi05** [comment]
up to #228

**Comment by ferdi05** [comment]
up until #124 #123 #122 #121 that are all related to #17
Spent 2 hours on this today so a lot of housekeeping. Somehow it feels more complex than newer issues, I guess that they got more accurate with more practice. I hope this won't get worse.

**Comment by ferdi05** [comment]
up to #95

**Comment by ferdi05** [comment]
up to #66

**Comment by ferdi05** [comment]
happy to say that it's done, everything was read through and sorted if needed.
