### ISSUE TITLE
Introduction blog post

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#3]
Write a blog post introducing yourself to the community. You can wait for #1 to be done before writing yours if you want an example or just do it as you please!

**Comment by fharper** [comment]
Once you are done, please tag @react-learner so he can review it. It will probably be a standard procedure for every text-based content we put out there.

**Comment by fharper** [comment]
Here is mine as an example: https://docs.google.com/document/d/1-eLyG5Ioae2VlUJYSPuZt9hNqD_ac1sAJldd-XlySao/edit#heading=h.fmvhen6qmekt

No need to do the same at all, and you don't have to share as much personal stuff as me.

**Comment by CaroFG** [comment]
Here's the link of mine: 
https://docs.google.com/document/d/1Rpj0mp5BXpL2OM4pvLu7DXQuUaSwG_o-3y0MKb2GT28/edit?usp=sharing
