### ISSUE TITLE
Add a `SUPPORT.md` file to our main repos

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#300]
See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project

Related to #280 

@CaroFG happy to discuss this at our next meeting

**Comment by CaroFG** [comment]
https://github.com/meilisearch/.github/pull/5

**Comment by CaroFG** [comment]
Closed by https://github.com/meilisearch/.github/pull/5
