### ISSUE TITLE
Check the `Writing your contributing guidelines` section

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#301]
Check https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines

**Comment by curquiza** [comment]
> There is no mention of the roadmap for instance. But there is on the GitHub org profile. We could link there

FYI, the roadmap is also linked in the README of MeiliSearch and in each SDK README.

> Do you thinks there is a need for a FAQ @curquiza ?

I don't think so. We add information and tips a collaborator (or an external contributor) might need, for example [tips for debugging in the Ruby SDK](https://github.com/meilisearch/meilisearch-ruby/blob/main/CONTRIBUTING.md#using-docker-compose-).

**Comment by ferdi05** [comment]
Thanks for your answer @curquiza 
> > There is no mention of the roadmap for instance. But there is on the GitHub org profile. We could link there
> 
> FYI, the roadmap is also linked in the README of MeiliSearch and in each SDK README.

Great! nothing to change about this then
> 
> > Do you thinks there is a need for a FAQ @curquiza ?
> 
> I don't think so. We add information and tips a collaborator (or an external contributor) might need, for example [tips for debugging in the Ruby SDK](https://github.com/meilisearch/meilisearch-ruby/blob/main/CONTRIBUTING.md#using-docker-compose-).

Very cool. let's keep this this way until we need to reassess this.
