### ISSUE TITLE
Create a demo with the MoMA artworks dataset

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#32]

**Comment by fharper** [comment]
the repo https://github.com/meilisearch/demo-MoMA

**Comment by CaroFG** [comment]
- [ ] Add highlighted results
- [ ] Create ascending and descending index to sort by date
- [ ] Create artist index

**Comment by fharper** [comment]
Since the code is now in a repo, we could add the next steps in issues there. I added those :)

**Comment by fharper** [comment]
Can you give me an idea of what's left for this demo?

**Comment by CaroFG** [comment]
Yes, once the sort-by-date PR is approved, I have to make some small changes to the design draft PR to ask for approval, and I hope it would be it. Maybe the tests on the setup.js file, if we really want them...
