### ISSUE TITLE
Add repobeats to our repos

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#322]
[Repobeats](https://repobeats.axiom.co/) is a way to embed contributor analytics into your GitHub project's README

**Comment by CaroFG** [comment]
We are currently waiting for their team to implement a feature that allows excluding contributors from the analytics. We don't want MeiliSearch organization members to appear, we only want external contributors to be showcased.

**Comment by ferdi05** [comment]
Repobeats team says it's ready. First test on `[instant-meilisearch](https://github.com/meilisearch/instant-meilisearch/pull/614)` repo.

**Comment by ferdi05** [comment]
As the stats don't look that great for `instant-meilisearch` repo, we're going to add them for [MeiliSearch](https://github.com/meilisearch/meilisearch) repo.
We're currently waiting for some help from Repobeats team as the current image still displays the contributions made by MeilISearch team members.

**Comment by ferdi05** [comment]
After more discussion with the _integration_ and _core_ teams, there are still drawbacks: showing that the MeiliSearch team is working on actively maintaining a repo and simultaneously rewarding the most active external contributors.
We're unsure that Repobeats is the right tool for this, so we're closing the issue from now on.
