### ISSUE TITLE
2022-03-16 - StrapiConf 2022

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#325]
Current discussion: [internal MeiliSearch Notion](https://www.notion.so/meilisearch/Organisation-CFP-f585038789d246478362ee5b4757bd8e)
Date: TBD
Hour: TBD
Venue: Online
MeiliSearch's role: Speaker
Attending team members: @bidoubiwa 
Topic: Gatsby + Strapi + MeiliSearch = ❤️
CFP: [link](https://docs.google.com/forms/d/e/1FAIpQLSfj2clqy7udvebnJl5IwTsvnnW8R1Cq89X8hfRESo5_OMvTCA/viewform)

**Comment by ferdi05** [comment]
Content was discussed by @bidoubiwa and @ferdi05 during two meetings.
@bidoubiwa will make a proposal by mid-December for:

- a title of the talk
- an abstract
- an outline

**Comment by ferdi05** [comment]
CFP was filled, based on this [Notion page](https://www.notion.so/meilisearch/Strapi-CFP-f585038789d246478362ee5b4757bd8e) _(private link)_.

**Comment by bidoubiwa** [comment]
I think this can be closed!

**Comment by ferdi05** [comment]
indeed thanks

**Comment by ferdi05** [comment]
We decided to sponsor the conference at a _Bronze_ level. See the sponsorship brochure [on Notion](https://www.notion.so/meilisearch/Events-1fd89bd590394d44af7c7db327e5c623#af90b05e90334bb58ff19e116d245209) _(private link)_.
