### ISSUE TITLE
Create your biography

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#34]
Since you'll start speaking at conferences at some point, you should take the time to create a bio. If you want I can brainstorm with you. Here is an example (you don't need all versions) https://docs.google.com/document/d/1kF4GmIrs3Ogxpe46ZpK_Q8LcVcYk3SjD6zYyHuUsjUg/edit#

**Comment by CaroFG** [comment]
Where should I write this bio? Github, blog?

**Comment by fharper** [comment]
Just add a link to the document here, not sure the structure of our repo data-wise yet.

**Comment by CaroFG** [comment]
https://docs.google.com/document/d/16V_kiMRyzOFC66oMKbTq1A5KPYiUk-R7sJSXj3pprMI/edit?usp=sharing
