### ISSUE TITLE
Create a Gatsby guide

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#340]
Some inspiration from [Algolia's guide](https://www.gatsbyjs.com/docs/adding-search-with-algolia)

**Comment by shivaylamba** [comment]
I have created a draft pull request on the Gatsby Github Repository ( https://github.com/gatsbyjs/gatsby/pull/34886 ). 

Currently waiting for review from the Gatsby team.

**Comment by shivaylamba** [comment]
PR on Gatsby repo closed as the Gatsby team requested to post this on our own blog site.

Currently in review by Tommy for posting on our blog site. ETA: 1st week of March
