### ISSUE TITLE
Submit to Gastby's plugins library

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#342]
See the marketplace [here](https://www.gatsbyjs.com/plugins/).
Check the [submission process](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/submit-to-plugin-library/)

**Comment by ferdi05** [comment]
Checklist before publication is filled, thanks @mdubus 

- [x] Publish a package to npm (learn how on the npm docs).
- [x] Include the required files in your plugin code.
- [x] Include a keywords field in your plugin’s package.json, containing gatsby and gatsby-plugin. If your plugin is a theme, please also include gatsby-theme.
- [x] Document your plugin with a README, using the contributing plugin template for reference.

**Comment by ferdi05** [comment]
@mdubus I'd love your advice on this, but it seems to me that Gatsby uses the keywords `gatsby` and `gatsby-plugin` for referencing the plugin, discovering the plugin from `npm`.
The submission process doesn't say that you need to submit the link to any form...
but our plugin is not referenced yet. I have no explanations as it looks like we are compliant with the process that they described.
Well to make it short, I have no idea why we're not on their library yet

**Comment by mdubus** [comment]
> @mdubus I'd love your advice on this, but it seems to me that Gatsby uses the keywords `gatsby` and `gatsby-plugin` for referencing the plugin, discovering the plugin from `npm`.
> The submission process doesn't say that you need to submit the link to any form...
> but our plugin is not referenced yet. I have no explanations as it looks like we are compliant with the process that they described.
> Well to make it short, I have no idea why we're not in their library yet.

Hi @ferdi05  ! 
For now the plugin isn't released yet, so it doesn't appear on NPM. Let's wait & see when it will be released if we appear on their library 😉

**Comment by ferdi05** [comment]
🤦‍♂️ thanks @mdubus

**Comment by ferdi05** [comment]
We're in the [plugin marketplace](https://www.gatsbyjs.com/plugins/gatsby-plugin-meilisearch). Closing the issue
