### ISSUE TITLE
Migration guide: from Algolia to Meilisearch

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#353]

**Comment by ferdi05** [comment]
We should discuss this in a meeting @qdequele @shivaylamba @ferdi05

**Comment by ferdi05** [comment]
## 2022-02-15 - Meeting with @qdequele @shivaylamba @ferdi05 

### General considerations
Users that want to migrate from Algolia to Meilisearch often have pricing considerations. We do not provide as many features as Algolia does.

Developers will have a more challenging time migrating to a new frontend rather than migrating to a new backend.
We should emphasize how simple it's easy to switch from Algolia to Meilisearch.

We could do something quite similar to the [Typesense's migration guide](https://typesense.org/docs/guide/migrating-from-algolia.html). But they are not providing the right marketing message, saying that Algolia is much better than Typesense and trying to fight with their pricing our support.

We don't have every feature that Algolia has, but in most cases, there are workarounds (for instance, multi-index search).
We could improve some visual features like range sliders (for instance, no max or min in the faceted search).

We could create a page dedicated to naming convention differences in the documentation website.
Former Algolia users will stick to Algolia's naming convention, and we need to make sure that they land on the right page.

We could have a glossary that compares our features' names with the names that alternative solution uses, [like Typesense's](https://typesense.org/docs/guide/migrating-from-algolia.html#equivalent-features-and-concepts). We would link to this page in the migration guide.

### Integrations 
Most of our users leverage our integrations to use Meilisearch. So we could assume that we should create a migration guide per integration. It would take longer, so it's not really what we are thinking of doing right now.
We have [the same integrations as Algolia](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#integrations-and-sdks) (except for Django). Migrating to a new SDK seems relatively straightforward.

We could create some content about using Laravel+react (only two lines of code to change to make it work). We could make it a video.

### Frontend
The migration can be done in one line of code on the frontend: substitute `instantsearch` with `instant-meilisearch` 
It could be a demo for a _wow effect_.

**The ultimate argument**: you don't need to have a dedicated person on it. A frontend developer working on this for 2-3 hours would be enough to test it.

### Next steps

- [ ] Create an outline, to be validated by @qdequele 
- [ ] Come up with a first draft, review, and iterate
- [ ] Discuss the naming convention comparison with @gmourier 
- [ ] Discuss the naming convention usage in the documentation website with @dichotommy

**Comment by gmourier** [comment]
Excellent idea

**Comment by shivaylamba** [comment]
Here is the [outline](https://www.notion.so/meilisearch/Migration-guide-from-Algolia-to-Meilisearch-26595bf49f9a4ca39d0ec1a57349e5a1)(private link) for the migration guide from Algolia to Meilisearch.

**Comment by ferdi05** [comment]
@shivaylamba is currently working on a [full version](https://www.notion.so/meilisearch/Algolia-to-Meilisearch-migration-guide-2ced0574d10e46438e0fc998fededd12) _(private link)_ of the guide.

**Comment by ferdi05** [comment]
Tutorial was published [in the documentation](https://docs.meilisearch.com/learn/getting_started/algolia_migration.html#overview).
It also lead to improvement in [the approach comparison](https://docs.meilisearch.com/learn/getting_started/algolia_migration.html#overview) in the comparison to our alternatives.

**Comment by flexchar** [comment]
Heads up @ferdi05 that links are 404. 

I also found this. https://www.meilisearch.com/docs/learn/update_and_migration/algolia_migration#settings-and-parameters-comparison

It would be nice to mention that page in algolia starts from 0 and in meili from 1. Furthermore, `attributesToSnippet` doesn't exist and there is no mention of forwarding client IP for analytics using `X-Forwarded-For` for when our client is proxied by our own backend for frontend.

**Comment by CaroFG** [comment]
Hello @flexchar,

Indeed, this is a very old issue and the documentation site and structure have changed a lot ever since. 

I have opened an [issue](https://github.com/meilisearch/documentation/issues/2822) in the documentation repo to add the info you have provided. 

If you see any additional info or improvement don't hesitate to open an issue yourself or a PR 😇
