### ISSUE TITLE
Demo/PR: Vercel Virtual Event Starter Kit

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#356]
Adding a searchbar to [Vercel Virtual Event Starter Kit](https://vercel.com/virtual-event-starter-kit)

**Comment by shivaylamba** [comment]
Here is a live demo link, where you can use Meilisearch to search for schedules, speakers, jobs, sponsors. 

Live Demo: https://next-js-event-starter-kit.vercel.app/

Also linked is the Github repository for this integration: 

Github Link: https://github.com/shivaylamba/NextJS-Event-Starter-Kit/

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19529592/154377691-737d5230-ca2b-425a-8bc1-e27dd45e7296.png">

**Comment by shivaylamba** [comment]
We have also created an issue on the official event-starter-kit repository to add a search integration using Meilisearch : https://github.com/vercel/virtual-event-starter-kit/issues/69

**Comment by shivaylamba** [comment]
I have also updated the README.md for installation steps.

**Comment by ferdi05** [comment]
As we haven't received any update from the Vercel team since March, I will close this issue (this could have been done sooner). @shivaylamba if you want to pick it up from here for some reasons, feel free to!

**Comment by shivaylamba** [comment]
Thanks @ferdi05 looks like there hasn't been any update yet as I didn't receive any response since last time.

**Comment by ferdi05** [comment]
Indeed. What I meant is that Meilisearch won't dig any further on this topic, so feel free to do anything you want of this

**Comment by shivaylamba** [comment]
Alright thanks Ferdinand
