### ISSUE TITLE
Create a demo for v0.26.0

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/devrel#358]
Create a demo to showcase the multi-tenant functionality in [Meilisearch](https://github.com/meilisearch/specifications/blob/scoped-api-keys/text/0089-tenant-tokens.md).

**Comment by shivaylamba** [comment]
Update:
I have read the documentation + specifications for the multi-tenancy feature in Meilisearch v0.26.0 and now started native implementation for testing out the multi-tenant functionality.

[MeilisearchJS](https://github.com/meilisearch/meilisearch-js) doesn't support v0.26.0 at the moment.

**Comment by shivaylamba** [comment]
Scope: 
According to @guimachiavelli 
Regarding the tenant token demo, we could have just a multi-tenancy demo and switching user account show that you can only have your documents as search results as the selected user. Simple and straightforward to show that Meilisearch can do that!

**Comment by shivaylamba** [comment]
Update: Started to work on the frontend design idea provided by @guimachiavelli 
![image](https://user-images.githubusercontent.com/19529592/156308373-74d6e582-07d5-431c-81c5-1d63d587eff5.png)

At the same time I have set up script to help seed data to meilisearch and today will proceed to add APIs to add tenant tokens for users.

**Comment by gmourier** [comment]
Hello @shivaylamba, thanks for the follow-up.

We discussed this demo with @qdequele a few days ago. We agreed on the fact that proposing the creation of a tenant token in the demo could make it complex and be more related to a technical demo.

If you still decide to go for the creation of a tenant token, I think it's worth it to involve product design in the UX.

What do you think about it? 

It could just be a switch of users who have tenant tokens already associated. E.g. `John` selector in the screenshot.

**Comment by shivaylamba** [comment]
Created Link: https://tenant-token-demo.vercel.app/

**Comment by shivaylamba** [comment]
Updates:
Currently making changes to the UI based on the suggestions made by Guillaume and Charline.

**Comment by shivaylamba** [comment]
![image](https://user-images.githubusercontent.com/19529592/158121730-ffc38840-d4ab-4ba9-87c0-8de9eb27fee4.png)
Final design changes requested by Charline 

Blog Post to be reviewed this week.

**Comment by ferdi05** [comment]
[published](https://blog.meilisearch.com/multi-tenancy/) by @shivaylamba
