### ISSUE TITLE
Creating an ITW template for our first user interviews

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#428]
Relying on our previous experience and online resources, we're building an interview template to create our first use cases. They may appear on our landing page as summarized versions before we try to create longer copies.

These first interviews should be led by @qdequele.

Curated resources:
- Hubspot guide: [How to Write a Case Study](https://blog.hubspot.com/blog/tabid/6307/bid/33282/the-ultimate-guide-to-creating-compelling-case-studies.aspx)
- [Gitlab customer case studies](https://about.gitlab.com/handbook/marketing/strategic-marketing/customer-reference-program/case-studies/)

_Tips:_
_- To craft a compelling story, we should focus on open-ended questions that invite elaboration, such as, "Can you describe ...?" or, "Tell me about ..."_
_- Look for facts and figures more than for feelings_

### On their business and role
- Quick description of their company and department
- What is your role within the company?
- How many employees work in your department?
- What are your current objectives?

### On their pain points
- What challenges are you trying to overcome with a search solution?
- What might have happened if you did not identify a solution?
- Before using Meilisearch, did you explore other solutions that did not work out? If so, what happened?

### On choosing Meilisearch
- How did you hear about Meilisearch?
- Who was involved in the selection process?
- How did you evaluate available options?
- What was most important to you when evaluating your options? Anything that makes Meilisearch stand out among its alternatives?

### On implementing Meilisearch
- Are you using a self-hosted version or Meilisearch Cloud? why?
  - If a self-hosted version, ask about the infra
  - If Meilisearch Cloud, what plan did you go for, and why?
- How long did it take to implement Meilisearch?
- Who took care of this? Who maintains it? Who customizes the settings?

### On using Meilisearch
- Does this meet your expectations?
- Is there a specificity of Meilisearch that you find super helpful compared to any other solution?

### On the results/challenges
If not replied yet, what challenges did you overcome thanks to Meilisearch?
- In what ways does that enhance your competitive advantage?
- How much have you increased your metrics?

**Comment by qdequele** [comment]
Thanks @ferdi05!
