### ISSUE TITLE
Consistency across demo styling

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#430]
It is something @shivaylamba started to think about when he created the [Tenant Token demo](https://tenant-token.meilisearch.com/): we could have a consistent styling across all our demos as they all have different styling.

This would be useful for many reasons:
- Users will recognize that this is an officially supported demo
- we'll have a boiler plate - and will not lose time wondering about styling - when creating a new demo

But this requires us to update demos that were created before (actually we're already working on updating them cc @oluademola).

cc @gmourier

**Comment by ferdi05** [comment]
@oluademola to list all different components of our demos.
Sync with @shivaylamba who already saw that with the Tenant token demo

**Comment by CaroFG** [comment]
It would save some time to have a template for demos with the basics, like a CSS file (with the style of the search bar, the search results, headings...), and assets like the Meilisearch logo. But if it takes too much time we can do without it, cause when you inspect on Figma you have the CSS info (it would be nice to have the sizes in rem though)

**Comment by shivaylamba** [comment]
Actually @oluademola did mention that having a common style file (CSS file) would be good. We can decide on some common styling across the various UI elements and export their css code and add it to this common file. 
@CaroFG @ferdi05 @oluademola

**Comment by CaroFG** [comment]
I think we can have a basic style sheet with elements that won't require a to of changes. I am thinking about the styling of headings, for instance, I guess that, if we want to keep it consistent, all <h1> elements should have the same size, weight, etc. The search bar too, maybe the search results cards too (border, shadow, background, those details...)

We could, eventually, create something similar to what Algolia did with their `instantsearch.css`

**Comment by shivaylamba** [comment]
I can take an initial version for creating this stylesheet and get it reviewed by @CaroFG and others.

**Comment by bidoubiwa** [comment]
Hey! instant-meilisearch already contains some styling rules for different type of environments. https://github.com/meilisearch/instant-meilisearch/blob/main/.eslintrc.js

They follow the styling decision of most of the other JS repos in the meilisearch scope. Maybe you could take inspiration from this :)

**Comment by ferdi05** [comment]
> I can take an initial version for creating this stylesheet and get it reviewed by @CaroFG and others.

please go ahead @shivaylamba

**Comment by shivaylamba** [comment]
PR has been created for some of the common UI elements in the demos repository, currently it is a draft PR as reviews/more UI elements can be added for the style guide.

**Comment by shivaylamba** [comment]
Suggestion: Regarding the CSS Style guide, This could be a good reference:  https://github.com/razorpay/blade
Essentially creating a Storybook for the Design guide

**Comment by shivaylamba** [comment]
https://www.figma.com/file/YUqMlOmApYd0D2aitPyDce/Guide-to-design-a-demo
