### ISSUE TITLE
Update slack community invitation mechanism

### ISSUE THREAD

**Issue by tpayet** [meilisearch/devrel#436]
To invite people to our Slack community we are using the URL `slack.meilisearch.com`

This URL is a redirection to an invite link that anyone already in Slack can generate from the workspace.

Today, some people told us they weren't able to join the slack community because the link expired. It appears that the link Slack generates can have no expiration date but will always be limited to 100 invitations.

-> We will have to update the redirection with a new link every 100 new people. I did it today to solve the issue asap but we need to find another mechanism to automatically update this invitation link.

**Comment by ferdi05** [comment]
Have we tought about using [Slackin](https://github.com/rauchg/slackin)?

**Comment by tpayet** [comment]
We used it at some point, but I don't remember why we switched from it 😬

**Comment by ferdi05** [comment]
We faced this problem again but fixed it.
Something to consider if we wanted to switch to another platform at some point.

**Comment by Luna-meili** [comment]
Following an investigation on social media as well as reaching out to the Slack support team, we have confirmation that the limitation of 100 people per invite is linked to the servers and cannot be adjusted on our Admin side (safety measures Slack implemented).

There is a possibility an Admin/owner of the Slack can reach out to the support team at feedback@slack.com and request a personalised link that they will generate on their end. Following my research, we can hope to go from 100 to 2000 people that can use the link (unclear if we can go above 2000, might be worth asking).

This will still require us to keep an eye on the link and re-update it whenever necessary, but it should grant us a more generous timeframe before our users run into the issue again.

When reaching out to the Slack support team, these are the points that need to be raised:

-our current limit of 100 people per link is worrisome for us as it offers a poor user experience and might stunt the growth of our Slack community.
-We have been informed that for safety measures, we cannot adjust that setting on our side
-However, we've also been advised that it is possible for the Slack team themselves to generate an invite link on our behalf with a higher cap (2000 people per invite, maybe more?)
-Please generate such a link for us, it would be a great benefit to the continued growth of our Slack channel

**Comment by ferdi05** [comment]
Just sent the email as an owner of the Slack community

**Comment by Luna-meili** [comment]
The button has now been updated! :)
Thanks very much for your hard work
