### ISSUE TITLE
Excerpt guidelines

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#453]
- Create guidelines to write an excerpt
- Apply them to posts without any excerpt
- Possibly rework some excerpt if needed

**Comment by ferdi05** [comment]
Will be needed for #364

**Comment by ferdi05** [comment]
We'll have to be careful with the SEO here. The excerpt of a blog post is used as the `<meta name="description>"` tag value.

**Comment by CaroFG** [comment]
Google best practices fro creating quality meta descriptions: https://developers.google.com/search/docs/appearance/snippet#meta-descriptions
