### ISSUE TITLE
URL guidelines

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#454]
- Guidelines on how to create the best URL (this has consequences on the SEO, or at least used to)

**Comment by ferdi05** [comment]
Will be needed for #364

**Comment by ferdi05** [comment]
https://www.semrush.com/blog/on-page-seo-basics-urls/

**Comment by CaroFG** [comment]
Also from: https://www.semrush.com/blog/what-is-a-url-slug/

Some good tips for URL structure also include:

- **Avoid placing a year in your URL.** You’ll be able to easily update the content without changing the URL. Any page authority or ranking the page has earned will be maintained and the content remains evergreen. If you do need dates in the URLs, just remember to redirect if you update to a new year.
- **Include keywords whenever possible.** The URL is a big flashing sign that tells search engines what your page is about. If someone searches “how to make a blueberry pie,” and the URL slug on your page is “how-to-make-a-blueberry-pie,” it obviously serves search intent. The URL states clearly what is on the page.
- **Be clear with the slug to avoid content duplication.** If you have similar URL slugs, Google may struggle to differentiate the page content, and hence choose not to serve either page up on a SERP. A [site audit](https://www.semrush.com/siteaudit/) can help avoid any URL parameter crawling issues.

**Comment by CaroFG** [comment]
Characteristics of a good meta description: https://yoast.com/meta-descriptions/#characteristics-of-a-good-meta-description

**Comment by CaroFG** [comment]
In a nutshell:
**The URL should state clearly what is on the page.**

DOs
- Keep it simple and descriptive
- Readable 
- Include keywords
- Short: around 3 to 5 words

DON'Ts
- Avoid using a year: to easily update the content and keep the ranking the page has earned
- Avoid having similar URLs slugs: search engine crawlers might think there's content duplication 
- Don't use non-ASCII characters like emojis
