### ISSUE TITLE
Rationalizing tags and providing guidelines

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#466]
There is no real rule for tags, and it's just up to the author's will so far. 
We should:

- [x] List all existing tags, and see if they are actually used (I guess this can be done through Ghost admin)
- [x] Define what are the guidelines (only one tag or are we allowing more? how can I add a new tag?...)
- [ ] Define a list of accepted tag (to be maintained)
- [ ] Update older content with the suitable tag(s)

**Comment by CaroFG** [comment]
Existing tags and number of posts associated

|  tag                  |  number of posts |
|-----------------------|------------------|
| airbyte               | 1                |
| charabia              | 1                |
| cloud                 | 1                |
| coder-history         | 1                |
| commongoals           | 1                |
| common-goals          | 1                |
| company               | 9                |
| comparison            | 1                |
| demo                  | 3                |
| devrel                | 4                |
| docs                  | 1                |
| elasticsearch         | 1                |
| facets                | 0                |
| gatsby                | 1                |
| getting-started       | 2                |
| goodreads             | 1                |
| hacktoberfest         | 6                |
| hacktoberfest2022     | 3                |
| interview             | 1                |
| introduction          | 1                |
| javascript            | 1                |
| language              | 1                |
| life-at-meilisearch   | 5                |
| meilisearch           | 1                |
| news                  | 0                |
| open-source           | 10               |
| placeholder           | 0                |
| product               | 2                |
| project-handobook     | 1                |
| rails                 | 1                |
| react                 | 2                |
| release               | 18               |
| search                | 2                |
| searchbar             | 2                |
| settings              | 0                |
| slack                 | 1                |
| story                 | 2                |
| strapi                | 2                |
| swag                  | 2                |
| team                  | 2                |
| tech                  | 2                |
| tokenizer             | 1                |
| tutorial              | 11               |
| vuepress              | 1                |

**Comment by CaroFG** [comment]
To start with we could get rid of all the tags with 0 and 1 posts related. This should leave us with 19 out of 44.
We could even get rid of tags with only 2 posts associated, which would leave 9 tags: 

- company
- demo
- devrel
- hacktoberfest
- hacktoberfest2022
- life-at-meilisearch
- open-source
- release
- tutorial

Then we should asses if they are still relevant and check our content to see where does each blog post fit, and create new tags if necessary

**Comment by CaroFG** [comment]
I just cleaned the tags, the following are the tags still available:
- company
- demo
- devrel
- hacktoberfest
- life-at-meilisearch
- open-source
- release
- tutorial

**Comment by CaroFG** [comment]
Two 2 have been added to the list: `meet-the-team` and `guide`. So currently the list looks like this:

- company
- demo
- devrel
- guide
- hacktoberfest
- life-at-meilisearch
- meet-the-team
- open-source
- release
- tutorial

**Comment by ferdi05** [comment]
Hey @CaroFG thanks for this good work.

Could you:

1. Give a description of these categories
2. Turn that into a process in the repo (meaning a file rather than an issue)
3. Include it in our blog process where it makes sense

**Comment by CaroFG** [comment]
Yes, of course, it is planned :)

**Comment by CaroFG** [comment]
After discussion with the team, we have decided on the following tags:
- `community`
- `company-news`
- `future-of-work`
- `meet-the-team`
- `release`
- `state-of-search`
- `tech-tools`
- `using-meilisearch`
