### ISSUE TITLE
Create a small description for languages testing

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#48]
Create a small text description for the people who will test MeiliSearch with Chinese, Japanese and Korean languages. Let's be clear on why we ask them to test, what they should test and the feedback we want. Either one version per language or just one if it's the same for everyone.

I'll add specific guidance on how to test once the instances are deployed.

**Comment by fharper** [comment]
Not sure who is the best person to do that, so I assigned it to @qdequele & @curquiza, so feel free to re-assign.

Would be nice if I can get the text by Wednesday at the latest.

**Comment by curquiza** [comment]
I'm personally not able at all to say what should be tested or the feedback we want.
However, I might help you find people to do the tests, but it does not seem to be the purpose of this issue 😄

**Comment by fharper** [comment]
Closing this for now since the Tokenizer isn't ready.
