### ISSUE TITLE
Idea: Add Meilisearch support for TasteJS Movies 

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/devrel#514]
What is TasteJS?
TasteJS is an open-source organization (https://github.com/tastejs) that has some popular projects like TodoMVC, and Movies which primarily focus on the implementation of projects in multiple JavaScript frameworks. 

One of the projects that they have is https://tastejs.com/movies/ where they showcase examples of using the TMDB dataset and showing sample applications in multiple Javascript frameworks like Nuxt, NextJS, etc. The search implementation in these examples uses React-Search and it is not a very intuitive search experience. We could introduce Meilisearch as an open-source search option for the TasteJS movies. This can lead to some additional user adoption since TasteJS is a popular open-source organization. 

cc @ferdi05 @mdubus

**Comment by ferdi05** [comment]
Thanks for this idea @shivaylamba.
Currently we don't have the bandwidth to take care of this, so if you or anyone would like to take care of this, we'll be happy to provide some light support.
