### ISSUE TITLE
Meilisearch contributors program

### ISSUE THREAD

**Issue by Luna-meili** [meilisearch/devrel#524]
Hello @krosenk729, @katherinefhc

My name is Luna and I am the Developer Community Lead at Meilisearch. I apologise for contacting you in such a way, I unfortunately didn't have access to a more private solution. : )

We hope you’re doing great and would like to extend an invitation to our MeiliStars Program. The MeiliStars program is a contributors initiative in which we would like to regroup key Meilisearch contributors and interact with each other in the spirit of conviviality and mutual growth. We aim to offer perks exclusive to the program participants - such as exclusive swag and a direct line to key people within the company for example- and hope you’ll want to join alongside the other participants!

What is expected of you? Not much aside from yourself! You can take part in as many activities as you wish and to the extent that you can. We’re inviting you because of your unique voice and your very own brand of input we observed on GitHub or on social media, and we’d love to have that in the program!

This is the very first Contributors program run by Meilisearch! Because of that, we would like to put in place a 6 months long program so we can test our various initiatives together and gather your feedback to adjust our formula and ensure the experience is worthwhile and engaging.

What do you think? Would you accept to be part of it? At the beginning of the program, we’ll happily present some of the activities and initiatives we’ve thought of, and you’ll be able to ask all the question that comes to mind.

We would love to have you with us, but should you not be able to join us, please don’t hesitate to let us know, we completely understand. : )

Looking forward to hearing back from you,

Luna

**Comment by CaroFG** [comment]
It looks like it's a Hacktoberfest contributor that isn't planning to keep contributing to the project. Orbit levels need to be improved.
