### ISSUE TITLE
Dead links in most MeiliSearch blog articles and related content

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/devrel#539]
With the addition of the new documentation a lot of links broke. I did not have time to mention it in the review.

I created a small tool to determine if urls are still valid: https://github.com/bidoubiwa/vuepress-plugin-external-link-checks

A lot of dead links have been found in the different SDK's, and blog articles. I saw you made a lot of PR in the different SDK's but it could be interesting for you to see all the other breaking links in all meilisearch related articles/pages.

Here is a small preview of the results but it is only a small part: 
<img width="1491" alt="Screenshot 2021-02-03 at 09 56 29" src="https://user-images.githubusercontent.com/33010418/106722340-20bc9980-6606-11eb-9511-aa5081ee2080.png">

We could maybe add this tool in the CI and the local tests.

**Comment by ferdi05** [comment]
@CaroFG transferred it, thanks!

**Comment by CaroFG** [comment]
Links were updated
