### ISSUE TITLE
Create the newsletter guidelines

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#54]
The WHO (target audience), the HOW (tools we will use, how to share information with us...), the WHEN (our calendar/timeframe), the WHAT (what a newsletter at MeiliSearch should look like)...

**Comment by fharper** [comment]
As a reference, here's what I shared with the MeiliSearch employees

> I created the channel #newsletter as we hope to be able to sent the first one at the beginning of 2021. A draft has already been written a couple of months ago, so we’ll start from there and adapt. I will need to help from everyone to share things in this channel that we should add to the newsletter. It could be:
> - new MeiliSearch release
> - introducing new team member
> - news about the company like the new office OR job opening OR recap of our Christmas party…
> - amazing tutorials or videos, related to search or not, that could interest our community
> - new cool tech or OSS projects you found (even if not new or not related to us)
>
> We want to have the proper mixed between our content and anything else interesting (more on that, I’ll eventually write the WHY, HOW, WHO, WHEN of the newsletter). I also would like to have a section for “community corner” where we highlight contributors, and where we share news our community want to share (example: Joe released a cool command line app he built)…
>
> There are a lot to do before we send the first one, but I want us all to start share things that could be in the first one, and keep this thinking starting for now… Without your help, there is no way we can make this happen with all the rest :)

**Comment by fharper** [comment]
It's P1 since #53 is one of my main priority for Q2

**Comment by ferdi05** [comment]
done
