### ISSUE TITLE
Evaluate a new blogging platform to replace Ghost

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#58]
I'll add more details tomorrow, but in the meantime, here is the little presentation I wanted to use to demonstrate what we have, what need/miss and what we will gain, in this case, with Wordpress.

https://docs.google.com/presentation/d/1IlWhl0fu7EfmhBvbvMPT0BAgPdlriAd0IXaXkI6Qv4s/edit?usp=sharing

**Comment by tpayet** [comment]
Same question as in #21 what are the key features we currently miss with Ghost that should justify the migration? :)

**Comment by fharper** [comment]
Same answer as #21 🤣

You can check the small presentation I created, but I'll add more details here tomorrow (was supposed to do it yesterday 😬)

**Comment by fharper** [comment]
This discussion is quite easy IMHO. Ghost is a great platform, but it may be too simple for our needs. It comes down to the [amazing number of plugins WordPress has](https://en-ca.wordpress.org/plugins/). Right now, I would love to add more automation, like [automatically optimizing the pictures in articles](https://en-ca.wordpress.org/plugins/shortpixel-image-optimiser/) (which I could do with GitHub actions), but more important, an [editorial calendar](https://wordpress.org/plugins/editorial-calendar/) integrated to our blogging platform, which will make the devrel life easier. Having this ecosystem of plugins makes us future-proof.

Day to day, **it won't change how writers use the platform**, and we have more chances to lower down the learning curves since WordPress is more well known.

If we have concern about the speed, I run my blog on a 5$ droplet on DO, but it's also possible to make WordPress headless.

Any other questions?

**Comment by tpayet** [comment]
I agree Wordpress might be a better fit for Meili :)
Let's migrate as soon as we have an editorial calendar, this way we will ensure we are not migrating for the sake of changing Ghost to Wordpress. What do you think?

**Comment by fharper** [comment]
The idea to have an integrated calendar into Wordpress is to be able to create the editorial calendar... in Wordpress 🤣

It's not just about that, but in any cases, we will have to brainstorm the blog post ideas before I have time to get Wordpress up & running.

**Comment by fharper** [comment]
Some examples:

**Comment by fharper** [comment]
Some examples of sites using Wordpress that have a great design: 
- Obama Foundation is running on Wordpress: https://www.obama.org/
- Angry Birds :rolling_on_the_floor_laughing: http://www.angrybirds.com/
- Studio Ouam (super creative site, love it) http://studioouam.com/en/
- Filmaker Jony Guedj http://www.jonyguedj.com/
- Awesome Motive (more tradition company & website, but still classy) https://awesomemotive.com/
- Artists site, full of animations and colours http://10x17.co/
- Semplice, click on other pages to see the design, but I personally love any typo first type of blog, it’s clean and minimalist https://www.semplice.com/

**Comment by fharper** [comment]
**It was decided in today's company meeting to move forward with the change to Wordpress!**

**Comment by fharper** [comment]
The evaluation is done, creating another issue for the technology move.
