### ISSUE TITLE
Create a process on using social media

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#6]
Right now everyone is connected directly to the account, but we also have the mention service. I need to see if it make sense to use it. Checking to create a calendar schedule and see how can people do request to publish on it.

**Comment by tpayet** [comment]
We used this twitter queue so far https://www.notion.so/meilisearch/c902d1cb1d054bdf8991c0c754105b49?v=0570b94d77a844508399500655055ed7 Not something we want to keep but you might want to know ^^

**Comment by fharper** [comment]
Sounds good! Thanks

**Comment by fharper** [comment]
From now on we are all gonna use Mention only. Documentation on how to use it is to be done.

**Comment by fharper** [comment]
I gave everyone "user" access.

**Comment by fharper** [comment]
So we are not using Mention anymore for social media, but it doesn't matter as for now I'm the only one managing them. Caro managed them when I'm OOO, so it's not a priority for now.

**Comment by ferdi05** [comment]
We created a process on [Notion](https://www.notion.so/meilisearch/Social-Media-Queue-f5ab593e972d49a891059e2e537be7fe) _(private link)_.
