### ISSUE TITLE
Transfer the Process freelance writers from Notion to here

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#69]
Let's be public about how we work with freelance writers so it will be easier for new ones, we may get suggestion to improve our process and it may help a company starting to work with freelancers.

private: https://www.notion.so/meilisearch/Process-freelance-writers-765162013ac74d96ac20ba92668d29e0

**Comment by ferdi05** [comment]
I don't think that we'll use freelance writer from now on, closing this
