### ISSUE TITLE
Find an alternative to Mention for Social Media

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#71]
I kinda like the tool at first, but the more I use, the less it seems appropriate for our needs.

There is no way to RT with comments on Twitter. The load time is super slow. There is no way to undo a RT. The UI (unread) is confusing. No explanation on the influence score (maybe I didn't find it). No way to change the week start day to Monday like normal folks 🤣

Even more important, they don't have a good customer support: I have unanswered questions I ask more than a month ago...

**Comment by tpayet** [comment]
We use mostly mention to know when people mention MeiliSearch on the web ^^ If we need another tool for social media management, maybe Buffer could be an alternative?

**Comment by fharper** [comment]
I've been recommended twice [Hootsuite](https://hootsuite.com/) by acquaintances in devrel. Last time I tried it was years ago, so I should give it another go.

**Comment by fharper** [comment]
So we won’t use Hootsuite. I tried it, and it's hard to track new replies or doesn't seem I can even access DM! Also the UX is not something I could live with 😬

**Comment by fharper** [comment]
Next try will be https://buffer.com/

**Comment by fharper** [comment]
I created a Buffer account. Waiting for them as I have issue adding LinkedIn & Twitter 😬

As for Instagram, I'll add it if I decide to use the tool, as we need someone with a Facebook account to do so... 🤦‍♂️
