### ISSUE TITLE
Write blog post about what's new on v0.18

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#74]

**Comment by bidoubiwa** [comment]
This was my process, feel free to use it or to change it 😊
 
```
### Where to communicate on the new Release and in which order:

- Documentation should be published on GitHub.
- Slack community should be first warned that the new release is out.
- After some time, we should communicate on Twitter with a blog post.
- If the release brings a lot of new features, consider publishing it on LinkedIn and reddit.

```

**Comment by fharper** [comment]
I'll add this into the repo (we want to be as public as possible). @react-learner if you have any details you want to add to this about publishing a new release doc side.

**Comment by fharper** [comment]
> This was my process, feel free to use it or to change it 😊
> 
> ```
> ### Where to communicate on the new Release and in which order:
> 
> - Documentation should be published on GitHub.
> - Slack community should be first warned that the new release is out.
> - After some time, we should communicate on Twitter with a blog post.
> - If the release brings a lot of new features, consider publishing it on LinkedIn and reddit.
> ```

See #77 for that.

**Comment by bidoubiwa** [comment]
I'm adding here the comment in made in #76 if it may help you on your first blog post Caro! 

>About the blog post, based a bit on what RUST does when ever they publish a new release: https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html, I try to be as explanatory as possible.
For example, about the tokenizer, I would explain a little how it works and what we had before. In order for users to observe that we are evolving. As it took us so long to make that change, it should be at least a bit praised.
So I would say:
> - new features (may they impact the user or not)
> - new addition to the API (clearly showing with example how to use it)
> - Breaking changes (for example the default value of the payload limit going from 10mb to 100mb is a breaking change that should be communicated).

>Those are all what I use to do, it is of course up to you guys to decide if this is a direction you like.
For the last bit of information, the release article is always popular when they are published. So I think people like to read what is new. So don't be shy :D
```

**Comment by fharper** [comment]
@CaroFG: can @react-learner & I review it?

**Comment by react-learner** [comment]
Reviewed, would like to take a second look before publication if possible.

**Comment by fharper** [comment]
https://blog.meilisearch.com/v0-18-0/

Congrats on the great blog post @CaroFG !
