### ISSUE TITLE
Create a guide on how we review the documentation PR

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#75]
Things like we check for typo, avoir personal pronouns, test the code demo... What is the English we wants (US, international)... We could add this to the devrel repo, and point to it in the CONTRIBUTORS files in the doc repo (or just put it directly into the doc repo contribution file - I created the issue here, since it's more like an administration thing, than the doc itself)

**Comment by bidoubiwa** [comment]
Here is what I was looking for, if that may inspire you:
- Simple English. English is the international language of coders but is not often their first language.
- Correct information. It is always a good thing that someone else checks the information. May it be by trying the code or by looking at other information sources (older guide, code in meilisearch-core, ..)
- Extended information when needed. Sometimes to understand something you just need to add a bit more explanations. If it is hard for you to understand, it will be as well for a new user. 
- Examples that make sense. Sometimes examples are not perfect to showcase this or that. Always question the relevance of an example.
- Should the new information also be added or changed somewhere else in the documentation? 
- Should this new page be linked somewhere else in the documentation? Or only in the navbar? And is this a good place to add this page?

**Comment by fharper** [comment]
@react-learner was it part of the doc you wrote about contributing to the documentation?

**Comment by fharper** [comment]
P1 because of the new Technical Writer joining our team hopefully soon
