### ISSUE TITLE
Update & publish the new release guide/steps for devrel

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#77]
based on what @bidoubiwa defined before us, I created a PR for that. I updated based on what I had in mind.

https://github.com/meilisearch/devrel/pull/76

@CaroFG please comment.

@react-learner please review the documentation part, and please, copyedit the text itself.

@bidoubiwa comments welcome based on your experience at MeiliSearch.

@curquiza I'll create the same for a new integration.

**Comment by curquiza** [comment]
> @curquiza I'll create the same for a new integration.

Not sure to understand what it means 😁

**Comment by fharper** [comment]
Food for thoughts @react-learner, but the MeiliSearch use Milestone to manage PR & commits for new version. I would prefer we use the same process. See https://github.com/meilisearch/MeiliSearch/milestone/15

**Comment by fharper** [comment]
> > @curquiza I'll create the same for a new integration.
> 
> Not sure to understand what it means 😁

We will create the same kind of guide for when a new integration is released or an awesome new feature worth sharing for one or more integrations. Clearer?

**Comment by curquiza** [comment]
Not sure this is exactly the kind of guide you want to write but here is what I already wrote:
- about the integration tools release: https://github.com/meilisearch/integration-guides/blob/master/guides/integration-tool-release.md
- about the pre-release-week: https://github.com/meilisearch/integration-guides/blob/master/guides/pre-release-week.md

**Comment by fharper** [comment]
Awesome guides! It's more for the after, what do we do in #devrel. Mostly about sharing the good work your team is doing :D
